Lesson5
KovalevVL/TMS_110121 pull request #2
Opened 2021-01-30 15:18 UTC by KovalevVL

2021-02-01 10:43 UTC, JonDorian reviewed
Нужно чутка подправить) а так все круто)

2021-02-01 10:43 UTC, JonDorian commented on lesson5/src/com/tms/Task11.java
>  public class Task11 {
В реализации этого задания, в условии проверил только деление числа на само себя и на 1цу, радом будет выдавать число от **0 до 3** - и тут конечно все будет прокатывать. Но если увеличить рандом хотя бы от **0 до 9**, то число допустим **6** будет делится и на самого себя и на **1** и на **2** и на **3**. т.е алгоритм работает, но может выдавать и 6 и 8 итд за простые числа.

2021-02-01 10:43 UTC, JonDorian commented on lesson5/src/com/tms/Task15BegginerChapter.java
> +        int z;
Переменная **z** нигде не используется)

2021-02-01 10:43 UTC, JonDorian commented on lesson5/src/com/tms/Task15BegginerChapter.java
> +        System.out.println(array[i]);
Из-за того, что в этом for **нет ограничивающих цикл скобок**, в середине выполнения программы (а она выполниться ровно на половину, не выдав перевернутый массив) выдаст Exception: ArrayIndexOutOfBoundsException.

2021-02-01 10:43 UTC, JonDorian commented on lesson5/src/com/tms/Task16BegginerChapter.java
> +        }
Тут циклы начинают счет с элемента (большего/меньшего) включительно, а по заданию - между (не включительно)

2021-02-01 10:50 UTC, JonDorian commented on lesson5/src/com/tms/Task14BegginerChapter.java
> +                imin = i;
Тут перед if не хватает присвоению переменной min значения индекса при условии что оно пока 0, при выполнении программы минимальное значение всегда 0 и индекс его 0 хотя по факту это не так.

2021-02-07 14:36 UTC, RomanKashenok requested changes

2021-02-07 14:36 UTC, RomanKashenok commented on lesson5/src/com/tms/Task11.java
> +            n = (int) (Math.random() * 20)+1;
do you really need different random number on every cycle iteration? 
remove it please

2021-02-07 14:36 UTC, RomanKashenok commented on lesson5/src/com/tms/Task11.java
> +            return;
move return to if(){...} statement. You need to stop your cycle in case of not simple number but not in other case

2021-02-07 14:36 UTC, RomanKashenok commented on lesson5/src/com/tms/Task14BegginerChapter.java
> +        for (i = 1; i < array.length; i++) {
You have lost first element in array

2021-02-07 14:36 UTC, RomanKashenok commented on lesson5/src/com/tms/Task17BegginerChapter.java
> +        int j;
assign cycle related variables directly in cycle please (i and j)

2021-02-12 09:22 UTC, RomanKashenok requested changes

2021-02-12 09:22 UTC, RomanKashenok commented on lesson5/src/com/tms/Task14BegginerChapter.java
> +        for (i = 0; i < array.length; i++) {
for (int i = 0; i < array.length; i++)

2021-02-12 09:23 UTC, RomanKashenok approved these changes

2021-02-12 10:01 UTC, merged